org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.2
minecraft_version_range=[26.2,26.3)

neo_version=26.2.0.0-beta
neo_version_range=[26.2.0.0-beta,)

loader_version_range=[4,)

mod_id=jeb
mod_name=JEB
mod_license=All Rights Reserved
mod_version=1.1.0-26.2
mod_group_id=jeb
mod_authors=Max Bel
mod_description=It is a lightweight alternative to mods like JEI (Just Enough Items).