org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.1
minecraft_version_range=[26.1.1,26.2)

neo_version=26.1.1.15-beta
neo_version_range=[26.1.1,)

loader_version_range=[4,)

mod_id=jeb
mod_name=JEB
mod_license=All Rights Reserved
mod_version=1.0.12-26.1.1
mod_group_id=jeb
mod_authors=Max Bel
mod_description=It is a lightweight alternative to mods like JEI (Just Enough Items).